baseurl = "https://tiagokrebs.github.io"
title = "Tiago Krebs"
theme = "hugo-theme-cleanwhite"
languageCode = "pt-br"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/taylor-vick-M5tzZtFCOfs-unsplash.jpg"
  title = "Software Engineering"
  slogan = "$ echo -e \"things I'm working on or pondering\""
  SEOTitle = "Tiago Krebs Blog"
  keyword = "Tiago, Krebs, Docker, Kubernetes, Go, Golang, Microservice, Kafka, Flink, Clilckhouse, Data, Science, Micromaster, Azion, Edge, Computing"
 
  # Sidebar settings
  sidebar_about_description = "Systems, Data & Software Engineer, Tech Manager."
  sidebar_avatar = "images/tiagokrebs.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 0 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/sarah-kilian-52jRtc2S_VE-unsplash.jpg"
  title_404 = "Oops..."

  omit_categories = false

#  [[params.addtional_menus]]
#  title =  "ABOUT"
#  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "krebstiago@gmail.com"
  linkedin       = "https://www.linkedin.com/in/tiagokrebs"
  github         = "https://github.com/tiagokrebs"